<internal_error>
<sub_system>ERR</sub_system>
<callstack>
	0x7f1bd5c26171: ccl_err + 0x8171 (_ZN15ERR_STACKWALKER15get_stack_traceEPPKviiPv + 0xb1)
	0x7f1bd5c28ff5: ccl_err + 0xaff5 (_Z14err_terminatorv + 0x4b)
	0x7f1bcd5fb796: stdc++.so.6 + 0x63796 (_ZN10__cxxabiv111__terminateEPFvvE + 0x6)
	0x7f1bcd5fb7c3: stdc++.so.6 + 0x637c3
	0x7f1bcd5fba36: stdc++.so.6 + 0x63a36 (__cxa_rethrow + 0x46)
	0x7f1c0c38db64: QtCore.so.4 + 0x1a5b64 (_ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE + 0x2f4)
	0x7f1c0c3927c4: QtCore.so.4 + 0x1aa7c4 (_ZN16QCoreApplication4execEv + 0xb4)
	   0x401dd8: quartus + 0x1dd8 (_Z8qgq_mainiPPKc + 0x68)
	0x7f1bd8486360: ccl_msg + 0x40360 (_Z15msg_main_threadPv + 0x10)
	0x7f1bd57ea02c: ccl_thr + 0x602c (thr_final_wrapper + 0xc)
	0x7f1bd848641c: ccl_msg + 0x4041c (_Z18msg_thread_wrapperPFPvS_ES_ + 0x62)
	0x7f1bd5e5a359: ccl_mem + 0xb359 (_Z18mem_thread_wrapperPFPvS_ES_ + 0x99)
	0x7f1bd5c26f98: ccl_err + 0x8f98 (_Z18err_thread_wrapperPFPvS_ES_ + 0x27)
	0x7f1bd57ea3f2: ccl_thr + 0x63f2 (thr_thread_wrapper + 0x15)
	0x7f1bd8488622: ccl_msg + 0x42622 (_Z12msg_exe_mainiPPKcPFiiS1_E + 0xa3)
	   0x401eaa: quartus + 0x1eaa (main + 0x26)
	0x7f1bccacaf45: c.so.6 + 0x21f45 (__libc_start_main + 0xf5)
	   0x401c89: quartus + 0x1c89
</callstack>
<error>*** Fatal Error: Unhandled Exception</error>
<date>Sat Apr  1 14:15:36 2017
</date>
<version>Version 16.0.0 Build 211 04/27/2016 SJ Standard Edition</version>
</internal_error>